openapi: 3.0.3
info:
  title: Auth API
  version: 1.0.0

paths:
  /auth/register:
    post:
      summary: User registration
      description: Регистрация пользователя по email и паролю.
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterRequest'
            examples:
              simple:
                summary: Пример регистрации
                value:
                  email: "user@example.com"
                  password: "StrongPass123"
                  name: "John Doe"
      responses:
        '201':
          description: Пользователь успешно зарегистрирован
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RegisterResponse'
        '400':
          description: Некорректные данные (email уже занят, слабый пароль и т.п.)
        '409':
          description: Пользователь с таким email уже существует
        '500':
          description: Внутренняя ошибка сервера

components:
  schemas:
    RegisterRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          description: Email пользователя
        password:
          type: string
          format: password
          description: Пароль
          minLength: 8
        name:
          type: string
          description: Отображаемое имя пользователя
      additionalProperties: false

    RegisterResponse:
      type: object
      description: Данные о созданном пользователе
      properties:
        id:
          type: string
          description: Идентификатор пользователя
        email:
          type: string
          format: email
        name:
          type: string
        createdAt:
          type: string
          format: date-time
      required:
        - id
        - email
        - createdAt
      additionalProperties: false
